/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './cocktail-page';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-params';
import * as import9 from '../../shared/cocktail-service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from 'ionic-angular/components/toolbar/toolbar';
import * as import13 from 'ionic-angular/components/navbar/navbar';
import * as import14 from 'ionic-angular/components/button/button';
import * as import15 from 'ionic-angular/components/menu/menu-toggle';
import * as import16 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from 'ionic-angular/components/icon/icon';
import * as import19 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import20 from 'ionic-angular/components/content/content';
import * as import21 from 'ionic-angular/components/card/card';
import * as import22 from 'ionic-angular/components/list/list';
import * as import23 from 'ionic-angular/components/item/item';
import * as import24 from 'ionic-angular/components/list/list-header';
import * as import25 from '@angular/common/src/directives/ng_for';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from 'ionic-angular/navigation/view-controller';
import * as import29 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import30 from 'ionic-angular/components/app/app';
import * as import31 from 'ionic-angular/navigation/nav-controller';
import * as import32 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import33 from 'ionic-angular/components/menu/menu-controller';
import * as import34 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import35 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import36 from 'ionic-angular/util/keyboard';
import * as import37 from '@angular/core/src/zone/ng_zone';
import * as import38 from 'ionic-angular/components/tabs/tabs';
import * as import39 from 'ionic-angular/gestures/gesture-controller';
import * as import40 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import41 from 'ionic-angular/util/form';
import * as import42 from '@angular/core/src/linker/template_ref';
import * as import43 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import44 from 'ionic-angular/components/grid/grid';
var renderType_CocktailPage_Host:import0.RenderComponentType = (null as any);
class _View_CocktailPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _CocktailPage_0_4:import3.CocktailPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CocktailPage_Host0,renderType_CocktailPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('cocktail-page',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CocktailPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CocktailPage_0_4 = new import3.CocktailPage(this.parentInjector.get(import8.NavParams),this.parentInjector.get(import9.CocktailService));
    this._appEl_0.initComponent(this._CocktailPage_0_4,([] as any[]),compView_0);
    compView_0.create(this._CocktailPage_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.CocktailPage) && (0 === requestNodeIndex))) { return this._CocktailPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_CocktailPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_CocktailPage_Host === (null as any))) { (renderType_CocktailPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_CocktailPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const CocktailPageNgFactory:import11.ComponentFactory<import3.CocktailPage> = new import11.ComponentFactory<import3.CocktailPage>('cocktail-page',viewFactory_CocktailPage_Host0,import3.CocktailPage);
const styles_CocktailPage:any[] = ([] as any[]);
var renderType_CocktailPage:import0.RenderComponentType = (null as any);
class _View_CocktailPage0 extends import1.AppView<import3.CocktailPage> {
  _el_0:any;
  _Header_0_3:import12.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import13.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import14.Button;
  _MenuToggle_4_5:import15.MenuToggle;
  _ToolbarItem_4_6:import16.ToolbarItem;
  _query_Button_4_0:import17.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import18.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ToolbarTitle_9_4:import19.ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Content_14_4:import20.Content;
  _text_15:any;
  _el_16:any;
  _Card_16_3:import21.Card;
  _text_17:any;
  _el_18:any;
  _CardContent_18_3:import21.CardContent;
  _text_19:any;
  _el_20:any;
  _List_20_3:import22.List;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _Item_22_4:import23.Item;
  _ListHeader_22_5:import24.ListHeader;
  _query_Label_22_0:import17.QueryList<any>;
  _query_Button_22_1:import17.QueryList<any>;
  _query_Icon_22_2:import17.QueryList<any>;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _List_29_3:import22.List;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _Item_31_4:import23.Item;
  _ListHeader_31_5:import24.ListHeader;
  _query_Label_31_0:import17.QueryList<any>;
  _query_Button_31_1:import17.QueryList<any>;
  _query_Icon_31_2:import17.QueryList<any>;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _TemplateRef_35_5:any;
  _NgFor_35_6:import25.NgFor;
  _text_36:any;
  _el_37:any;
  _List_37_3:import22.List;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import2.AppElement;
  _Item_39_4:import23.Item;
  _ListHeader_39_5:import24.ListHeader;
  _query_Label_39_0:import17.QueryList<any>;
  _query_Button_39_1:import17.QueryList<any>;
  _query_Icon_39_2:import17.QueryList<any>;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _anchor_43:any;
  /*private*/ _appEl_43:import2.AppElement;
  _TemplateRef_43_5:any;
  _NgFor_43_6:import25.NgFor;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CocktailPage0,renderType_CocktailPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Header(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import28.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import29.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Navbar(this.parentInjector.get(import30.App),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import31.NavController,(null as any)),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import32.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import14.Button('','',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import15.MenuToggle(this.parentInjector.get(import33.MenuController),new import27.ElementRef(this._el_4),this.parentInjector.get(import28.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import16.ToolbarItem(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import12.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import17.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import18.Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import2.AppElement(9,2,this,this._el_9);
    var compView_9:any = import34.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import19.ToolbarTitle(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import12.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'',(null as any));
    compView_9.create(this._ToolbarTitle_9_4,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_14 = new import2.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import35.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import20.Content(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import30.App),this.parentInjector.get(import36.Keyboard),this.parentInjector.get(import37.NgZone),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import38.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_16_3 = new import21.Card(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-card-content',(null as any));
    this._CardContent_18_3 = new import21.CardContent();
    this._text_19 = this.renderer.createText(this._el_18,'\n\n    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-list',(null as any));
    this._List_20_3 = new import22.List(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_20),this.renderer,this.parentInjector.get(import39.GestureController));
    this._text_21 = this.renderer.createText(this._el_20,'\n      ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','item');
    this._appEl_22 = new import2.AppElement(22,20,this,this._el_22);
    var compView_22:any = import40.viewFactory_Item0(this.viewUtils,this.injector(22),this._appEl_22);
    this._Item_22_4 = new import23.Item(this.parentInjector.get(import41.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_22),this.renderer);
    this._ListHeader_22_5 = new import24.ListHeader(this.parentInjector.get(import26.Config),this.renderer,new import27.ElementRef(this._el_22),(null as any));
    this._query_Label_22_0 = new import17.QueryList<any>();
    this._query_Button_22_1 = new import17.QueryList<any>();
    this._query_Icon_22_2 = new import17.QueryList<any>();
    this._appEl_22.initComponent(this._Item_22_4,([] as any[]),compView_22);
    this._text_23 = this.renderer.createText((null as any),'\n        Instructions\n      ',(null as any));
    this._query_Label_22_0.reset(([] as any[]));
    this._Item_22_4.contentLabel = this._query_Label_22_0.first;
    compView_22.create(this._Item_22_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_23]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_25 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_18,'p',(null as any));
    this.renderer.setElementAttribute(this._el_26,'padding','');
    this._text_27 = this.renderer.createText(this._el_26,'',(null as any));
    this._text_28 = this.renderer.createText(this._el_18,'\n\n    ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_18,'ion-list',(null as any));
    this._List_29_3 = new import22.List(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_29),this.renderer,this.parentInjector.get(import39.GestureController));
    this._text_30 = this.renderer.createText(this._el_29,'\n      ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','item');
    this._appEl_31 = new import2.AppElement(31,29,this,this._el_31);
    var compView_31:any = import40.viewFactory_Item0(this.viewUtils,this.injector(31),this._appEl_31);
    this._Item_31_4 = new import23.Item(this.parentInjector.get(import41.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_31),this.renderer);
    this._ListHeader_31_5 = new import24.ListHeader(this.parentInjector.get(import26.Config),this.renderer,new import27.ElementRef(this._el_31),(null as any));
    this._query_Label_31_0 = new import17.QueryList<any>();
    this._query_Button_31_1 = new import17.QueryList<any>();
    this._query_Icon_31_2 = new import17.QueryList<any>();
    this._appEl_31.initComponent(this._Item_31_4,([] as any[]),compView_31);
    this._text_32 = this.renderer.createText((null as any),'\n        Ingredients\n      ',(null as any));
    this._query_Label_31_0.reset(([] as any[]));
    this._Item_31_4.contentLabel = this._query_Label_31_0.first;
    compView_31.create(this._Item_31_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_32]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._appEl_35 = new import2.AppElement(35,18,this,this._anchor_35);
    this._TemplateRef_35_5 = new import42.TemplateRef_(this._appEl_35,viewFactory_CocktailPage1);
    this._NgFor_35_6 = new import25.NgFor(this._appEl_35.vcRef,this._TemplateRef_35_5,this.parentInjector.get(import43.IterableDiffers),this.ref);
    this._text_36 = this.renderer.createText(this._el_18,'\n\n    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_18,'ion-list',(null as any));
    this._List_37_3 = new import22.List(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_37),this.renderer,this.parentInjector.get(import39.GestureController));
    this._text_38 = this.renderer.createText(this._el_37,'\n      ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','item');
    this._appEl_39 = new import2.AppElement(39,37,this,this._el_39);
    var compView_39:any = import40.viewFactory_Item0(this.viewUtils,this.injector(39),this._appEl_39);
    this._Item_39_4 = new import23.Item(this.parentInjector.get(import41.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_39),this.renderer);
    this._ListHeader_39_5 = new import24.ListHeader(this.parentInjector.get(import26.Config),this.renderer,new import27.ElementRef(this._el_39),(null as any));
    this._query_Label_39_0 = new import17.QueryList<any>();
    this._query_Button_39_1 = new import17.QueryList<any>();
    this._query_Icon_39_2 = new import17.QueryList<any>();
    this._appEl_39.initComponent(this._Item_39_4,([] as any[]),compView_39);
    this._text_40 = this.renderer.createText((null as any),'\n        Tools\n      ',(null as any));
    this._query_Label_39_0.reset(([] as any[]));
    this._Item_39_4.contentLabel = this._query_Label_39_0.first;
    compView_39.create(this._Item_39_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_40]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._anchor_43 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._appEl_43 = new import2.AppElement(43,18,this,this._anchor_43);
    this._TemplateRef_43_5 = new import42.TemplateRef_(this._appEl_43,viewFactory_CocktailPage2);
    this._NgFor_43_6 = new import25.NgFor(this._appEl_43.vcRef,this._TemplateRef_43_5,this.parentInjector.get(import43.IterableDiffers),this.ref);
    this._text_44 = this.renderer.createText(this._el_18,'\n  \n  ',(null as any));
    this._text_45 = this.renderer.createText(this._el_16,'\n',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_14.create(this._Content_14_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._el_16,
        this._text_46
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_47 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._anchor_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import14.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import15.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import16.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import19.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4; }
    if (((token === import13.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4; }
    if (((token === import12.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3; }
    if (((token === import23.Item) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Item_22_4; }
    if (((token === import24.ListHeader) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._ListHeader_22_5; }
    if (((token === import22.List) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._List_20_3; }
    if (((token === import23.Item) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Item_31_4; }
    if (((token === import24.ListHeader) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ListHeader_31_5; }
    if (((token === import22.List) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._List_29_3; }
    if (((token === import42.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import25.NgFor) && (35 === requestNodeIndex))) { return this._NgFor_35_6; }
    if (((token === import23.Item) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Item_39_4; }
    if (((token === import24.ListHeader) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ListHeader_39_5; }
    if (((token === import22.List) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._List_37_3; }
    if (((token === import42.TemplateRef) && (43 === requestNodeIndex))) { return this._TemplateRef_43_5; }
    if (((token === import25.NgFor) && (43 === requestNodeIndex))) { return this._NgFor_43_6; }
    if (((token === import21.CardContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._CardContent_18_3; }
    if (((token === import21.Card) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Card_16_3; }
    if (((token === import20.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Content_14_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_14_4.ngOnInit(); }
    changes = (null as any);
    const currVal_10:any = this.context.cocktail.ingredients;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgFor_35_6.ngForOf = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgFor_35_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_35_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_11:any = this.context.cocktail.tools;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgFor_43_6.ngForOf = currVal_11;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_11,currVal_11);
      this._expr_11 = currVal_11;
    }
    if ((changes !== (null as any))) { this._NgFor_43_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_43_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_22_1.dirty) {
        this._query_Button_22_1.reset(([] as any[]));
        this._Item_22_4._buttons = this._query_Button_22_1;
        this._query_Button_22_1.notifyOnChanges();
      }
      if (this._query_Icon_22_2.dirty) {
        this._query_Icon_22_2.reset(([] as any[]));
        this._Item_22_4._icons = this._query_Icon_22_2;
        this._query_Icon_22_2.notifyOnChanges();
      }
      if (this._query_Button_31_1.dirty) {
        this._query_Button_31_1.reset(([] as any[]));
        this._Item_31_4._buttons = this._query_Button_31_1;
        this._query_Button_31_1.notifyOnChanges();
      }
      if (this._query_Icon_31_2.dirty) {
        this._query_Icon_31_2.reset(([] as any[]));
        this._Item_31_4._icons = this._query_Icon_31_2;
        this._query_Icon_31_2.notifyOnChanges();
      }
      if (this._query_Button_39_1.dirty) {
        this._query_Button_39_1.reset(([] as any[]));
        this._Item_39_4._buttons = this._query_Button_39_1;
        this._query_Button_39_1.notifyOnChanges();
      }
      if (this._query_Icon_39_2.dirty) {
        this._query_Icon_39_2.reset(([] as any[]));
        this._Item_39_4._icons = this._query_Icon_39_2;
        this._query_Icon_39_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_22_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_31_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_39_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'',this.context.cocktail.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_10,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Content_14_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import4.interpolate(1,'',this.context.cocktail.descriptionPlain,'');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_27,currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._Content_14_4.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_CocktailPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.CocktailPage> {
  if ((renderType_CocktailPage === (null as any))) { (renderType_CocktailPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_CocktailPage,{})); }
  return new _View_CocktailPage0(viewUtils,parentInjector,declarationEl);
}
class _View_CocktailPage1 extends import1.AppView<any> {
  _el_0:any;
  _Row_0_3:import44.Row;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import23.Item;
  _ItemContent_2_5:import23.ItemContent;
  _query_Label_2_0:import17.QueryList<any>;
  _query_Button_2_1:import17.QueryList<any>;
  _query_Icon_2_2:import17.QueryList<any>;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CocktailPage1,renderType_CocktailPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_0_3 = new import44.Row();
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'width-50','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import40.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import23.Item(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import23.ItemContent();
    this._query_Label_2_0 = new import17.QueryList<any>();
    this._query_Button_2_1 = new import17.QueryList<any>();
    this._query_Icon_2_2 = new import17.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_3]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_2_4; }
    if (((token === import23.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_2_5; }
    if (((token === import44.Row) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Row_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.textPlain,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_CocktailPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_CocktailPage1(viewUtils,parentInjector,declarationEl);
}
class _View_CocktailPage2 extends import1.AppView<any> {
  _el_0:any;
  _Row_0_3:import44.Row;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import23.Item;
  _ItemContent_2_5:import23.ItemContent;
  _query_Label_2_0:import17.QueryList<any>;
  _query_Button_2_1:import17.QueryList<any>;
  _query_Icon_2_2:import17.QueryList<any>;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CocktailPage2,renderType_CocktailPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_0_3 = new import44.Row();
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'width-50','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import40.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import23.Item(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import23.ItemContent();
    this._query_Label_2_0 = new import17.QueryList<any>();
    this._query_Button_2_1 = new import17.QueryList<any>();
    this._query_Icon_2_2 = new import17.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_3]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_2_4; }
    if (((token === import23.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_2_5; }
    if (((token === import44.Row) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Row_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.text,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_CocktailPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_CocktailPage2(viewUtils,parentInjector,declarationEl);
}